// HTML Pareto Analysis
// Step 3 prototype: the full Pareto page rendered by one DAX measure as inline SVG.
// Host visual: HTML Content (lite). Drop this measure into the Content field well.
// Classic Pareto: ranked revenue bars + cumulative % line + dashed 80% threshold.
// Bars inside the 80% band render in TrailPeak green (the vital few), the rest gray.
// Uses the tie-safe [Product Rank] / [Cumulative Revenue %] measures from the model.

HTML Pareto Analysis =
VAR _w = 1000
VAR _h = 400
VAR _padL = 84
VAR _padR = 56
VAR _padT = 26
VAR _padB = 88
VAR _plotW = _w - _padL - _padR
VAR _plotH = _h - _padT - _padB
VAR _prods = FILTER ( ALLSELECTED ( dim_product ), NOT ISBLANK ( [Product Revenue] ) )
VAR _nAll = COUNTROWS ( _prods )
VAR _n80 = COUNTROWS ( FILTER ( _prods, [Cumulative Revenue %] < 0.80 ) ) + 1
VAR _nBars = MIN ( _nAll, 20 )
VAR _top = FILTER ( _prods, [Product Rank] <= _nBars )
VAR _nShown = COUNTROWS ( _top )
VAR _maxRev = MAXX ( _top, [Product Revenue] )
VAR _step = DIVIDE ( _plotW, _nShown )
VAR _barW = _step * 0.68
VAR _lastClosedRaw = [Last Closed Date]
VAR _lastClosed = IF ( ISBLANK ( _lastClosedRaw ), MAX ( dim_date[Date] ), _lastClosedRaw )
VAR _firstData = CALCULATE ( MIN ( fact_pnl_actuals[Date] ), REMOVEFILTERS () )
VAR _period =
    IF (
        HASONEVALUE ( dim_date[YearMonthKey] ),
        SELECTEDVALUE ( dim_date[YearMonthLabel] ),
        FORMAT ( MAX ( MIN ( dim_date[Date] ), _firstData ), "MMM YYYY" ) & " to "
            & FORMAT ( MIN ( MAX ( dim_date[Date] ), _lastClosed ), "MMM YYYY" )
    )
VAR _scope =
    SWITCH (
        TRUE (),
        HASONEVALUE ( dim_store[StoreName] ), SELECTEDVALUE ( dim_store[StoreName] ),
        HASONEVALUE ( dim_store[Region] ), SELECTEDVALUE ( dim_store[Region] ) & " Region",
        "All Stores"
    )
VAR _bars =
    CONCATENATEX (
        _top,
        VAR _r = [Product Rank]
        VAR _x = _padL + ( _r - 1 ) * _step + ( _step - _barW ) / 2
        VAR _bh = DIVIDE ( [Product Revenue], _maxRev ) * _plotH
        VAR _y = _padT + _plotH - _bh
        VAR _cx = _x + _barW / 2
        VAR _labY = _padT + _plotH + 16
        VAR _fill = IF ( [Cumulative Revenue %] <= 0.80, "#2d6a4f", "#cbd5e1" )
        RETURN
            "<rect x='" & ROUND ( _x, 1 ) & "' y='" & ROUND ( _y, 1 )
                & "' width='" & ROUND ( _barW, 1 ) & "' height='" & ROUND ( _bh, 1 )
                & "' rx='3' fill='" & _fill & "'/>"
                & "<text x='" & ROUND ( _cx, 1 ) & "' y='" & _labY
                & "' transform='rotate(-38 " & ROUND ( _cx, 1 ) & " " & _labY
                & ")' text-anchor='end' font-size='12' fill='#64748b'>"
                & LEFT ( dim_product[ProductName], 12 ) & "</text>",
        ,
        [Product Rank], ASC
    )
VAR _linePoints =
    CONCATENATEX (
        _top,
        VAR _cx = _padL + ( [Product Rank] - 1 ) * _step + _step / 2
        VAR _cy = _padT + ( 1 - [Cumulative Revenue %] ) * _plotH
        RETURN ROUND ( _cx, 1 ) & "," & ROUND ( _cy, 1 ),
        " ",
        [Product Rank], ASC
    )
VAR _dots =
    CONCATENATEX (
        _top,
        VAR _r = [Product Rank]
        VAR _cx = _padL + ( _r - 1 ) * _step + _step / 2
        VAR _cy = _padT + ( 1 - [Cumulative Revenue %] ) * _plotH
        RETURN
            "<circle cx='" & ROUND ( _cx, 1 ) & "' cy='" & ROUND ( _cy, 1 )
                & "' r='3' fill='#d97706'/>"
                & IF (
                    _r = 1 || MOD ( _r, 5 ) = 0,
                    "<text x='" & ROUND ( _cx, 1 ) & "' y='" & ROUND ( _cy - 8, 1 )
                        & "' text-anchor='middle' font-size='11.5' fill='#b45309'>"
                        & FORMAT ( [Cumulative Revenue %], "0%" ) & "</text>",
                    ""
                ),
        ,
        [Product Rank], ASC
    )
VAR _gridlines =
    CONCATENATEX (
        { 0.25, 0.50, 0.75, 1.00 },
        VAR _gy = _padT + ( 1 - [Value] ) * _plotH
        RETURN
            "<line x1='" & _padL & "' y1='" & ROUND ( _gy, 1 ) & "' x2='" & ( _w - _padR )
                & "' y2='" & ROUND ( _gy, 1 ) & "' stroke='#eef2f7' stroke-width='1'/>"
                & "<text x='" & ( _w - _padR + 8 ) & "' y='" & ROUND ( _gy + 3.5, 1 )
                & "' font-size='12' fill='#94a3b8'>" & FORMAT ( [Value], "0%" ) & "</text>",
        ""
    )
VAR _y80 = _padT + 0.2 * _plotH
RETURN
    IF (
        _nAll = 0,
        "<div style='font-family:""Segoe UI"", sans-serif; color:#64748b; padding:24px;'>No product sales in the current selection.</div>",
        "<div style='font-family:""Segoe UI"", sans-serif; background:#ffffff; border:1px solid #e2e8f0; border-radius:12px; padding:16px 22px; height:calc(100vh - 6px); box-sizing:border-box; overflow:hidden; display:flex; flex-direction:column;'>"
            & "<div style='display:flex; justify-content:space-between; align-items:baseline; margin-bottom:2px;'>"
            & "<div style='font-size:19px; font-weight:700; color:#0f172a;'>Product Revenue Pareto</div>"
            & "<div style='font-size:12px; font-weight:600; letter-spacing:0.06em; text-transform:uppercase; color:#2d6a4f;'>TrailPeak Outfitters</div>"
            & "</div>"
            & "<div style='font-size:13px; color:#64748b; margin-bottom:8px;'>Top "
            & _nShown & " of " & _nAll & " products &#183; " & _period & " &#183; " & _scope & "</div>"
            & "<div style='display:inline-block; font-size:13px; font-weight:600; color:#2d6a4f; background:#f4faf6; border:1px solid #cde3d6; border-radius:999px; padding:4px 12px; margin-bottom:10px;'>"
            & _n80 & " of " & _nAll & " products drive 80% of revenue</div>"
            & "<div style='flex:1 1 auto; min-height:0; margin-top:4px;'><svg viewBox='0 0 " & _w & " " & _h & "' width='100%' height='100%' preserveAspectRatio='xMidYMid meet' style='display:block;' xmlns='http://www.w3.org/2000/svg'>"
            & _gridlines
            & _bars
            & "<line x1='" & _padL & "' y1='" & ROUND ( _y80, 1 ) & "' x2='" & ( _w - _padR )
            & "' y2='" & ROUND ( _y80, 1 )
            & "' stroke='#d97706' stroke-width='1.4' stroke-dasharray='6 4'/>"
            & "<polyline points='" & _linePoints
            & "' fill='none' stroke='#d97706' stroke-width='2.2'/>"
            & _dots
            & "</svg></div>"
            & "<div style='margin-top:10px; font-size:11.5px; color:#94a3b8;'>"
            & "Green bars are the vital few inside the 80% band &#183; amber line is cumulative revenue share &#183; "
            & [Data Through Label]
            & " &#183; HTML prototype, production visual ships in Deneb</div>"
            & "</div>"
    )
